name: test


save_dir: "saved/"


dataset:
    type: EventFrameDataset
    args:
        event_dir: "data/events.h5"
        steering_angle_dir: "data/steering_can.csv"
        integration_time: 0.05 #seconds
        partial_range:
        # out of 46840070, or leave empty to test everything
        # when the partial range is set so that the last batch has only one frame,
        # the batchnorm of model will throw an error


data_loader:
    type: DataLoader
    args:
        batch_size: 32
        test_split: 0.1
        num_workers: 8

optimizer:
    type: Adam
    args:
        lr: 0.1

trainer:
    verbosity: 2
    epochs: 20

loss: mse_loss

metrics:
    - RMSE
    - EVA


logger:
    version: 1
    formatters:
        simple:
            format: '%(message)s'
        detailed:
            format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    handlers:
        console:
            class: logging.StreamHandler
            level: DEBUG
            formatter: simple
            stream: ext://sys.stdout
        file_handler:
            class: logging.handlers.RotatingFileHandler
            level: INFO
            formatter: detailed
            filename: info.log
            maxBytes: 10485760
            backupCount: 20
            encoding: utf8
    root:
        level: INFO
        handlers:
            - console
            - file_handler
    # question: if logger isn't specified does it inherit the same handlers as root?
