name: test

save_dir: "saved/"

dataset:
    type: EventFrameDataset
    args:
        event_dir: "data/events.h5"
        steering_angle_dir: "data/steering_can.csv"
        integration_time: 0.05 #seconds
        max_pixel_value: 17

data_loader:
    type: DataLoader
    args:
        batch_size: 32
        test_split: 0.2
        num_workers: 8

optimizer:
    type: Adam
    args:
        lr: 0.01

scheduler:
    type: StepLR
    args:
        step_size: 5
        gamma: 0.2

trainer:
    verbosity: 2
    epochs: 50
    save_period: 5
    monitor: 'min val_RMSE'
    early_stop: 10

loss: mse_loss

metrics:
    - RMSE
    - EVA

logger:
    version: 1
    formatters:
        simple:
            format: '%(message)s'
        detailed:
            format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    handlers:
        console:
            class: logging.StreamHandler
            level: DEBUG
            formatter: simple
            stream: ext://sys.stdout
        file_handler:
            class: logging.handlers.RotatingFileHandler
            level: INFO
            formatter: detailed
            filename: info.log
            maxBytes: 10485760
            backupCount: 20
            encoding: utf8
    root:
        level: INFO
        handlers:
            - console
            - file_handler
